import Link from 'next/link'
import { ArrowRight, Check, Layers3, ShieldCheck, Sparkles } from 'lucide-react'
import { createClient } from '@/lib/server'

const features = [['One workspace', 'Customers, projects, tasks, files, and invoices in one calm place.'], ['Built for teams', 'Clear ownership, thoughtful permissions, and a record of every important change.'], ['Focus on the work', 'A fast, visual command centre that makes next steps obvious.']]

export default async function Home() { const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); const workspaceHref = user ? '/dashboard' : '/auth/sign-up'; return <main className="min-h-screen bg-[#fafafa] text-zinc-950 selection:bg-indigo-200">
  <nav className="mx-auto flex h-20 max-w-7xl items-center justify-between px-6"><Link href="/" className="flex items-center gap-2 font-semibold tracking-tight"><span className="grid size-8 place-items-center rounded-lg bg-zinc-950 text-white"><Layers3 size={16}/></span>FlowDesk</Link><div className="flex items-center gap-3">{user ? <><span className="hidden text-sm text-zinc-500 sm:block">Signed in as {user.email}</span><Link href="/dashboard" className="rounded-lg bg-zinc-950 px-4 py-2 text-sm font-medium text-white transition hover:bg-zinc-700">Open dashboard</Link></> : <><Link href="/auth/login" className="hidden text-sm font-medium text-zinc-600 sm:block">Sign in</Link><Link href="/auth/sign-up" className="rounded-lg bg-zinc-950 px-4 py-2 text-sm font-medium text-white transition hover:bg-zinc-700">Start for free</Link></>}</div></nav>
  <section className="mx-auto max-w-7xl px-6 pb-24 pt-20 text-center sm:pt-28"><div className="mx-auto mb-6 flex w-fit items-center gap-2 rounded-full border border-zinc-200 bg-white px-3 py-1 text-xs font-medium text-zinc-600 shadow-sm"><Sparkles size={13} className="text-indigo-600"/>The operating system for modern teams</div><h1 className="mx-auto max-w-4xl text-5xl font-semibold tracking-[-0.055em] sm:text-7xl">Manage your entire business workflow in one place.</h1><p className="mx-auto mt-7 max-w-2xl text-lg leading-8 text-zinc-600">FlowDesk brings your customers, projects, tasks, and cashflow together—so your team can move with clarity.</p><div className="mt-10 flex flex-col justify-center gap-3 sm:flex-row"><Link href={workspaceHref} className="inline-flex items-center justify-center gap-2 rounded-lg bg-indigo-600 px-5 py-3 text-sm font-medium text-white shadow-lg shadow-indigo-200 transition hover:bg-indigo-500">{user ? 'Open your dashboard' : 'Build your workspace'} <ArrowRight size={16}/></Link><a href="#how-it-works" className="rounded-lg border border-zinc-200 bg-white px-5 py-3 text-sm font-medium shadow-sm transition hover:bg-zinc-50">See how it works</a></div><div className="mx-auto mt-16 max-w-5xl overflow-hidden rounded-2xl border border-zinc-200 bg-white p-3 shadow-2xl shadow-zinc-200/70"><div className="rounded-xl bg-zinc-950 p-5 text-left text-white sm:p-8"><div className="flex gap-2"><i className="size-2.5 rounded-full bg-rose-400"/><i className="size-2.5 rounded-full bg-amber-400"/><i className="size-2.5 rounded-full bg-emerald-400"/></div><div className="mt-10 grid gap-4 sm:grid-cols-3"><div className="rounded-xl bg-white/10 p-4"><p className="text-xs text-zinc-400">Open projects</p><p className="mt-2 text-3xl font-semibold">12</p><p className="mt-3 text-xs text-emerald-300">↑ 18% this month</p></div><div className="rounded-xl bg-white/10 p-4 sm:col-span-2"><p className="text-xs text-zinc-400">This week</p><div className="mt-5 flex h-16 items-end gap-2">{[30,48,35,70,55,86,64].map((h,i)=><i key={i} className="w-full rounded-t bg-indigo-400" style={{height:`${h}%`}}/>)}</div></div></div></div></div></section>
  <section className="border-y border-zinc-200 bg-white py-24"><div className="mx-auto max-w-7xl px-6"><p className="text-center text-sm font-medium text-zinc-500">ONE SYSTEM. EVERY DAY-TO-DAY WORKFLOW.</p><div className="mt-12 grid gap-5 md:grid-cols-3">{features.map(([title,body],i)=><article key={title} className="rounded-xl border border-zinc-200 p-6"><span className="grid size-10 place-items-center rounded-lg bg-indigo-50 text-indigo-600">{i === 0 ? <Layers3 size={19}/> : i === 1 ? <ShieldCheck size={19}/> : <Sparkles size={19}/>}</span><h2 className="mt-5 text-lg font-semibold">{title}</h2><p className="mt-2 leading-7 text-zinc-600">{body}</p></article>)}</div></div></section>
  <section id="how-it-works" className="mx-auto grid max-w-7xl gap-12 px-6 py-24 md:grid-cols-2"><div><p className="text-sm font-semibold text-indigo-600">HOW IT WORKS</p><h2 className="mt-3 text-4xl font-semibold tracking-tight">From a new lead to a paid invoice.</h2></div><ol className="space-y-7">{['Create your company workspace and invite your team.','Turn customer needs into clear, owned project work.','See delivery and revenue without stitching tools together.'].map((item,i)=><li key={item} className="flex gap-4"><span className="grid size-7 shrink-0 place-items-center rounded-full bg-zinc-950 text-xs font-semibold text-white">{i+1}</span><p className="pt-0.5 text-zinc-600">{item}</p></li>)}</ol></section>
  <section className="bg-zinc-950 px-6 py-24 text-white"><div className="mx-auto max-w-3xl text-center"><p className="text-sm font-medium text-indigo-300">SIMPLE, TRANSPARENT PRICING</p><h2 className="mt-3 text-4xl font-semibold tracking-tight">One plan for teams that want momentum.</h2><p className="mt-4 text-zinc-400">Start free. Upgrade when your workflow grows.</p><div className="mt-8 inline-flex items-center gap-2 rounded-lg bg-white px-5 py-3 text-sm font-medium text-zinc-950"><Check size={16} className="text-emerald-600"/>No credit card required</div></div></section><footer className="mx-auto flex max-w-7xl items-center justify-between px-6 py-8 text-sm text-zinc-500"><span>© 2026 FlowDesk</span><span>Work flows better together.</span></footer>
</main> }
