'use client'
import { useState } from 'react'
import { useForm } from 'react-hook-form'
import { z } from 'zod'
import { zodResolver } from '@hookform/resolvers/zod'
import { Layers3, LoaderCircle } from 'lucide-react'
import { createOrganization } from '@/app/(app)/actions'
const schema=z.object({name:z.string().min(2,'Enter your company name'),slug:z.string().min(3,'Use at least 3 characters').regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/,'Use lowercase letters, numbers, and hyphens.')});type Values=z.infer<typeof schema>
export function OnboardingForm({email}:{email:string}){const [message,setMessage]=useState('');const {register,handleSubmit,formState:{errors,isSubmitting}}=useForm<Values>({resolver:zodResolver(schema),defaultValues:{name:'',slug:''}});const onSubmit=async(v:Values)=>{const r=await createOrganization(v);if(r)setMessage(r.message)};return <form onSubmit={handleSubmit(onSubmit)} className="w-full max-w-md rounded-2xl border border-zinc-200 bg-white p-7 shadow-xl shadow-zinc-200/60 dark:border-zinc-800 dark:bg-zinc-900"><div className="grid size-9 place-items-center rounded-lg bg-zinc-950 text-white"><Layers3 size={17}/></div><h1 className="mt-6 text-2xl font-semibold tracking-tight">Set up your workspace</h1><p className="mt-2 text-sm leading-6 text-zinc-500">You’re signed in as {email}. Create the company workspace your team will use.</p><div className="mt-6 grid gap-4"><label className="grid gap-1.5 text-sm font-medium">Company name<input {...register('name')} className="rounded-lg border px-3 py-2 dark:bg-zinc-950" placeholder="ABC Digital Agency"/>{errors.name&&<small className="text-red-600">{errors.name.message}</small>}</label><label className="grid gap-1.5 text-sm font-medium">Workspace URL<span className="flex overflow-hidden rounded-lg border"><span className="bg-zinc-100 px-3 py-2 text-sm text-zinc-500 dark:bg-zinc-800">flowdesk/</span><input {...register('slug')} className="min-w-0 flex-1 bg-transparent px-3 py-2 outline-none" placeholder="abc-digital"/></span>{errors.slug&&<small className="text-red-600">{errors.slug.message}</small>}</label></div>{message&&<p className="mt-4 text-sm text-red-600">{message}</p>}<button disabled={isSubmitting} className="mt-6 inline-flex w-full items-center justify-center gap-2 rounded-lg bg-indigo-600 px-4 py-2.5 text-sm font-medium text-white disabled:opacity-60">{isSubmitting&&<LoaderCircle size={16} className="animate-spin"/>}{isSubmitting?'Creating workspace...':'Create workspace'}</button></form>}
