'use client'
import { useState } from 'react'
import { useForm } from 'react-hook-form'
import { z } from 'zod'
import { zodResolver } from '@hookform/resolvers/zod'
import { Plus, X, LoaderCircle } from 'lucide-react'
import { createProject } from '@/app/(app)/actions'
const schema=z.object({name:z.string().min(1,'Project name is required'),description:z.string(),deadline:z.string()});type Values=z.infer<typeof schema>
export function ProjectForm(){const [open,setOpen]=useState(false);const [message,setMessage]=useState('');const {register,handleSubmit,formState:{errors,isSubmitting},reset}=useForm<Values>({resolver:zodResolver(schema),defaultValues:{name:'',description:'',deadline:''}});const submit=async(v:Values)=>{const r=await createProject(v);setMessage(r.message);if(r.ok){reset();setTimeout(()=>setOpen(false),500)}};return <><button onClick={()=>setOpen(true)} className="inline-flex items-center gap-2 rounded-lg bg-zinc-950 px-3.5 py-2.5 text-sm font-medium text-white dark:bg-white dark:text-zinc-950"><Plus size={16}/>New project</button>{open&&<div className="fixed inset-0 z-[60] grid place-items-center bg-black/40 p-4"><form onSubmit={handleSubmit(submit)} className="w-full max-w-md rounded-xl bg-white p-6 shadow-2xl dark:bg-zinc-900"><div className="flex justify-between"><div><h2 className="font-semibold">Create project</h2><p className="mt-1 text-sm text-zinc-500">Set up a space for your team’s work.</p></div><button type="button" onClick={()=>setOpen(false)}><X size={18}/></button></div><div className="mt-5 grid gap-4"><label className="grid gap-1.5 text-sm font-medium">Project name<input {...register('name')} className="rounded-lg border px-3 py-2 dark:bg-zinc-950" autoFocus/>{errors.name&&<small className="text-red-600">{errors.name.message}</small>}</label><label className="grid gap-1.5 text-sm font-medium">Description<textarea {...register('description')} className="min-h-20 rounded-lg border px-3 py-2 dark:bg-zinc-950"/></label><label className="grid gap-1.5 text-sm font-medium">Deadline<input type="date" {...register('deadline')} className="rounded-lg border px-3 py-2 dark:bg-zinc-950"/></label></div>{message&&<p className={`mt-3 text-sm ${message.includes('success')?'text-emerald-600':'text-red-600'}`}>{message}</p>}<button disabled={isSubmitting} className="mt-6 inline-flex w-full justify-center gap-2 rounded-lg bg-indigo-600 py-2.5 text-sm font-medium text-white">{isSubmitting&&<LoaderCircle size={16} className="animate-spin"/>}{isSubmitting?'Creating...':'Create project'}</button></form></div>}</>}
