'use client'

import { useState } from 'react'
import { BarChart, Bar, ResponsiveContainer, Tooltip, XAxis, AreaChart, Area, PieChart, Pie, Cell } from 'recharts'
import { ArrowUpRight, CheckCircle2, Clock3, FileText, Filter, MoreHorizontal, Plus, Search, SlidersHorizontal, Users, FolderKanban, Receipt, CircleDollarSign, Upload, Send, Check, AlertCircle } from 'lucide-react'
import { CustomerForm } from '@/components/customer-form'
import { ProjectForm } from '@/components/project-form'
import { TaskForm } from '@/components/task-form'
import { moveTask } from '@/app/(app)/actions'
import { InvoiceForm } from '@/components/invoice-form'

type Kind = 'dashboard'|'customers'|'projects'|'tasks'|'invoices'|'team'|'notifications'|'activity'|'settings'
const revenue = [{m:'Apr',v:8000},{m:'May',v:11800},{m:'Jun',v:9600},{m:'Jul',v:14500},{m:'Aug',v:13200},{m:'Sep',v:18400}]
const customers = [{name:'Acme Corporation',email:'hello@acme.co',company:'Acme Co.',status:'ACTIVE',value:'$18,400'},{name:'Northstar Studio',email:'team@northstar.io',company:'Northstar',status:'LEAD',value:'$6,200'},{name:'Mosaic Labs',email:'contact@mosaic.dev',company:'Mosaic',status:'ACTIVE',value:'$12,800'}]
const projects = [{name:'Website redesign',customer:'Acme Corporation',progress:72,status:'ACTIVE',due:'Oct 24',members:['AM','JS','LK']},{name:'Product launch',customer:'Northstar Studio',progress:35,status:'ACTIVE',due:'Nov 08',members:['AM','DC']},{name:'Brand system',customer:'Mosaic Labs',progress:100,status:'COMPLETED',due:'Oct 03',members:['JS','LK']}]
const taskColumns = [{name:'TODO', tasks:[['Define homepage narrative','HIGH'],['Source new product imagery','MEDIUM']]},{name:'IN PROGRESS',tasks:[['Build responsive landing page','URGENT'],['Prepare customer interview guide','LOW']]},{name:'REVIEW',tasks:[['Review analytics dashboard','HIGH']]},{name:'DONE',tasks:[['Set up project workspace','MEDIUM']]}]

function Title({title,description,action}:{title:string;description:string;action?:string}){return <div className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-2xl font-semibold tracking-tight">{title}</h1><p className="mt-1 text-sm text-zinc-500">{description}</p></div>{action&&<button className="inline-flex items-center gap-2 rounded-lg bg-zinc-950 px-3.5 py-2.5 text-sm font-medium text-white transition hover:bg-zinc-700 dark:bg-white dark:text-zinc-950"><Plus size={16}/>{action}</button>}</div>}
function Badge({children}:{children:string}) { const color=children==='ACTIVE'||children==='PAID'||children==='DONE'||children==='COMPLETED'?'bg-emerald-50 text-emerald-700':children==='HIGH'||children==='URGENT'||children==='OVERDUE'?'bg-rose-50 text-rose-700':'bg-amber-50 text-amber-700'; return <span className={`rounded-full px-2 py-0.5 text-[11px] font-semibold ${color}`}>{children.replace('_',' ')}</span> }
function Empty({title,body}:{title:string;body:string}) {return <div className="grid min-h-72 place-items-center rounded-xl border border-dashed border-zinc-300 bg-white p-8 text-center dark:border-zinc-700 dark:bg-zinc-900"><div><div className="mx-auto grid size-11 place-items-center rounded-xl bg-indigo-50 text-indigo-600"><FolderKanban size={20}/></div><h3 className="mt-4 font-medium">{title}</h3><p className="mt-1 max-w-xs text-sm text-zinc-500">{body}</p></div></div>}
function Toolbar(){return <div className="mb-4 flex flex-wrap gap-2"><label className="flex h-9 min-w-52 items-center gap-2 rounded-lg border border-zinc-200 bg-white px-3 text-sm text-zinc-500 dark:border-zinc-800 dark:bg-zinc-900"><Search size={15}/><input className="w-full bg-transparent outline-none" placeholder="Search..."/></label><button className="inline-flex items-center gap-2 rounded-lg border border-zinc-200 bg-white px-3 text-sm dark:border-zinc-800 dark:bg-zinc-900"><Filter size={14}/>Filter</button><button className="inline-flex items-center gap-2 rounded-lg border border-zinc-200 bg-white px-3 text-sm dark:border-zinc-800 dark:bg-zinc-900"><SlidersHorizontal size={14}/>View</button></div>}

function Dashboard({data}:{data:any}){const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);return <><Title title="Workspace overview" description="Live totals from your FlowDesk organization."/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{[['Total customers',data.customers,Users],['Active projects',data.projects,FolderKanban],['Pending tasks',data.tasks,Clock3],['Revenue',money(data.revenue),CircleDollarSign],['Outstanding',money(data.outstanding),Receipt]].map(([label,value,Icon])=>{const I=Icon as typeof Users;return <article key={label as string} className="rounded-xl border border-zinc-200 bg-white p-4 shadow-sm dark:border-zinc-800 dark:bg-zinc-900"><div className="flex justify-between text-sm text-zinc-500"><span>{label as string}</span><I size={16}/></div><p className="mt-4 text-2xl font-semibold tracking-tight">{value as string}</p><p className="mt-2 text-xs text-zinc-500">Current workspace</p></article>})}</div><div className="mt-5 grid gap-5 xl:grid-cols-3"><section className="rounded-xl border border-zinc-200 bg-white p-5 shadow-sm xl:col-span-2 dark:border-zinc-800 dark:bg-zinc-900"><h2 className="font-medium">Revenue overview</h2><p className="mt-1 text-sm text-zinc-500">Monthly revenue trend</p><div className="mt-6 h-60"><ResponsiveContainer><AreaChart data={revenue}><XAxis dataKey="m" tickLine={false} axisLine={false} tick={{fontSize:12,fill:'#71717a'}}/><Tooltip/><Area dataKey="v" type="monotone" stroke="#4f46e5" strokeWidth={2.5} fill="#c7d2fe"/></AreaChart></ResponsiveContainer></div></section><section className="rounded-xl border border-zinc-200 bg-white p-5 shadow-sm dark:border-zinc-800 dark:bg-zinc-900"><h2 className="font-medium">Start here</h2><p className="mt-2 text-sm text-zinc-500">Build your workflow in three steps.</p><div className="mt-5 space-y-3 text-sm"><a href="/customers" className="block rounded-lg bg-zinc-50 p-3 dark:bg-zinc-800">1. Add a customer →</a><a href="/projects" className="block rounded-lg bg-zinc-50 p-3 dark:bg-zinc-800">2. Create a project →</a><a href="/tasks" className="block rounded-lg bg-zinc-50 p-3 dark:bg-zinc-800">3. Add tasks →</a></div></section></div></>}
function Customers({items}:{items:any[]}){return <><div className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-2xl font-semibold tracking-tight">Customers</h1><p className="mt-1 text-sm text-zinc-500">Manage the companies and people you work with.</p></div><CustomerForm/></div><Toolbar/>{items.length===0?<Empty title="No customers yet" body="Add your first customer to start building relationships."/>:<div className="overflow-hidden rounded-xl border border-zinc-200 bg-white shadow-sm dark:border-zinc-800 dark:bg-zinc-900"><table className="w-full text-left text-sm"><thead className="border-b border-zinc-100 bg-zinc-50 text-xs uppercase tracking-wide text-zinc-500 dark:border-zinc-800 dark:bg-zinc-950"><tr><th className="p-4 font-medium">Customer</th><th className="hidden p-4 font-medium md:table-cell">Company</th><th className="p-4 font-medium">Status</th><th className="p-4"/></tr></thead><tbody>{items.map(c=><tr key={c.id} className="border-b border-zinc-100 last:border-0 hover:bg-zinc-50 dark:border-zinc-800 dark:hover:bg-zinc-800/50"><td className="p-4"><b className="block font-medium">{c.name}</b><span className="text-xs text-zinc-500">{c.email}</span></td><td className="hidden p-4 text-zinc-600 md:table-cell">{c.company ?? '—'}</td><td className="p-4"><Badge>{c.status}</Badge></td><td className="p-4"><button><MoreHorizontal size={17}/></button></td></tr>)}</tbody></table></div>}</>}
function Projects({items}:{items:any[]}){return <><div className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-2xl font-semibold tracking-tight">Projects</h1><p className="mt-1 text-sm text-zinc-500">Coordinate work, people, and deadlines.</p></div><ProjectForm/></div><Toolbar/>{items.length===0?<Empty title="No projects yet" body="Create a project, add work, and bring your team together."/>:<div className="grid gap-4 lg:grid-cols-3">{items.map(p=><article key={p.id} className="rounded-xl border border-zinc-200 bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md dark:border-zinc-800 dark:bg-zinc-900"><div className="flex justify-between"><Badge>{p.status}</Badge><button><MoreHorizontal size={17}/></button></div><h2 className="mt-5 font-semibold">{p.name}</h2><p className="mt-1 text-sm text-zinc-500">{p.customers?.name ?? 'No customer attached'}</p><div className="mt-6 h-1.5 overflow-hidden rounded-full bg-zinc-100 dark:bg-zinc-800"><div className="h-full w-1/12 rounded-full bg-indigo-600"/></div><div className="mt-2 flex justify-between text-xs text-zinc-500"><span>Just started</span><span>{p.deadline ? `Due ${p.deadline}` : 'No deadline'}</span></div><div className="mt-5 flex items-center justify-between"><span className="text-xs text-zinc-500">{p.project_members?.length ?? 0} members</span><a href={`/projects/${p.id}`} className="text-xs font-medium text-indigo-600">Open project →</a></div></article>)}</div>}</>}
function Tasks({data}:{data:{tasks:any[];projects:{id:string;name:string}[]}}){const labels=['TODO','IN_PROGRESS','REVIEW','DONE'] as const;const [drag,setDrag]=useState<string|null>(null);const [local,setLocal]=useState(data.tasks);const drop=async(status:typeof labels[number])=>{if(!drag)return;setLocal(x=>x.map(t=>t.id===drag?{...t,status}:t));await moveTask(drag,status);setDrag(null)};return <><div className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-2xl font-semibold tracking-tight">Tasks</h1><p className="mt-1 text-sm text-zinc-500">Drag work across the board as it moves forward.</p></div><TaskForm projects={data.projects}/></div>{data.projects.length===0?<Empty title="Create a project first" body="Tasks belong to a project. Create one to start planning work."/>:<div className="grid min-w-[900px] grid-cols-4 gap-4 overflow-x-auto pb-4">{labels.map(status=>{const list=local.filter(t=>t.status===status);return <section key={status} onDragOver={e=>e.preventDefault()} onDrop={()=>drop(status)} className="rounded-xl bg-zinc-100/80 p-3 dark:bg-zinc-900"><div className="mb-3 flex items-center justify-between px-1"><span className="text-xs font-semibold tracking-wide text-zinc-600 dark:text-zinc-300">{status.replace('_',' ')}</span><span className="grid size-5 place-items-center rounded bg-white text-[10px] text-zinc-500 dark:bg-zinc-800">{list.length}</span></div><div className="space-y-3">{list.map(t=><article draggable onDragStart={()=>setDrag(t.id)} key={t.id} className="cursor-grab rounded-lg border border-zinc-200 bg-white p-3 shadow-sm active:cursor-grabbing dark:border-zinc-800 dark:bg-zinc-950"><Badge>{t.priority}</Badge><h3 className="mt-3 text-sm font-medium leading-5">{t.title}</h3><div className="mt-4 text-xs text-zinc-500">{t.due_date ? `Due ${t.due_date}` : 'No due date'}</div></article>)}</div></section>})}</div>}</>}
function Invoices({data}:{data:{invoices:any[];customers:any[]}}){return <><div className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-2xl font-semibold tracking-tight">Invoices</h1><p className="mt-1 text-sm text-zinc-500">Track billing and keep cashflow moving.</p></div><InvoiceForm customers={data.customers}/></div><Toolbar/>{data.invoices.length===0?<Empty title="No invoices yet" body="Create an invoice from a customer to start tracking revenue."/>:<div className="overflow-hidden rounded-xl border border-zinc-200 bg-white shadow-sm dark:border-zinc-800 dark:bg-zinc-900"><table className="w-full text-left text-sm"><thead className="border-b bg-zinc-50 text-xs uppercase text-zinc-500 dark:bg-zinc-950"><tr><th className="p-4">Invoice</th><th className="p-4">Customer</th><th className="hidden p-4 sm:table-cell">Due date</th><th className="p-4">Status</th><th className="p-4 text-right">Amount</th></tr></thead><tbody>{data.invoices.map(i=><tr key={i.id} className="border-b last:border-0 dark:border-zinc-800"><td className="p-4 font-medium"><a href={`/invoices/${i.id}`}>{i.invoice_number}</a></td><td className="p-4 text-zinc-600">{i.customers?.name}</td><td className="hidden p-4 text-zinc-500 sm:table-cell">{i.due_date ?? '—'}</td><td className="p-4"><Badge>{i.status}</Badge></td><td className="p-4 text-right font-medium">${Number(i.total).toFixed(2)}</td></tr>)}</tbody></table></div>}</>}
function Simple({kind}:{kind:Kind}) {const config={team:['Team members','Invite collaborators and control access.',['Hasib Rahman','Sarah Chen','Daniel Cole']],notifications:['Notifications','Stay on top of activity that needs your attention.',['Sarah completed “Build responsive landing page”','Invoice INV-0246 is overdue','You were added to Website redesign']],activity:['Activity','A complete record of work across your organization.',['Hasib created a new project','Sarah completed a task','Daniel sent invoice INV-0248']],settings:['Settings','Manage your workspace and personal preferences.',['Organization profile','Members & permissions','Profile & security']]} as const;const [title,desc,items]=config[kind as keyof typeof config];return <><Title title={title} description={desc} action={kind==='team'?'Invite member':undefined}/><div className="rounded-xl border border-zinc-200 bg-white shadow-sm dark:border-zinc-800 dark:bg-zinc-900">{items.map((item,i)=><div key={item} className="flex items-center justify-between border-b border-zinc-100 p-5 last:border-0 dark:border-zinc-800"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-full bg-indigo-100 text-xs font-semibold text-indigo-700">{kind==='team'?item.split(' ').map(x=>x[0]).join(''):<CheckCircle2 size={17}/>}</span><div><p className="text-sm font-medium">{item}</p><p className="mt-0.5 text-xs text-zinc-500">{kind==='team'?(i===0?'Owner':'Member'):(kind==='activity'?'Today, 10:42 AM':'Manage preferences and updates')}</p></div></div>{kind==='notifications'&&<button className="text-xs text-indigo-600">Mark read</button>}{kind==='settings'&&<ArrowUpRight size={16} className="text-zinc-400"/>}</div>)}</div></>}
export function WorkspacePage({kind,data}:{kind:Kind;data?:any}){if(kind==='dashboard')return <Dashboard data={data ?? {customers:0,projects:0,tasks:0,revenue:0,outstanding:0}}/>;if(kind==='customers')return <Customers items={data ?? []}/>;if(kind==='projects')return <Projects items={data ?? []}/>;if(kind==='tasks')return <Tasks data={data ?? {tasks:[],projects:[]}}/>;if(kind==='invoices')return <Invoices data={data ?? {invoices:[],customers:[]}}/>;return <Simple kind={kind}/>}
